// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { OrchardDto } from "@/src/pie/dto/orchard.ts";
import type { FruitDto } from "@/src/pie/dto/fruit.ts";
import { Fruit } from "@/src/pie/domain/business/fruit/mod.ts";

// Coordinator for [REQ] fruit.gather(OrchardDto): FruitDto.
export async function gather(input: OrchardDto): Promise<FruitDto> {

  // core — pure business logic, no I/O
  const out = gatherCore(input);

  return out.result;
}

// Pure business logic for fruit.gather — no I/O. Takes the
// request input; returns the result.
function gatherCore(input: OrchardDto): { result: FruitDto } {
  const fruit = new Fruit();
  return { result: { fruitId: "fruit-7" } };
}
