// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { RollDoughDto } from "@/src/pie/dto/roll-dough.ts";
import type { CrustDto } from "@/src/pie/dto/crust.ts";
import { Crust } from "@/src/pie/domain/business/crust/mod.ts";

// Coordinator for [REQ] crust.roll(RollDoughDto): CrustDto.
export async function roll(input: RollDoughDto): Promise<CrustDto> {

  // core — pure business logic, no I/O
  const out = rollCore(input);

  return out.result;
}

// Pure business logic for crust.roll — no I/O. Takes the
// request input; returns the result.
function rollCore(input: RollDoughDto): { result: CrustDto } {
  const crust = new Crust();
  return { result: { crustId: `crust-${input.fillingId}` } };
}
