// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { BakeDto } from "@/src/pie/dto/bake.ts";
import type { BakedPieDto } from "@/src/pie/dto/baked-pie.ts";
import { BakedPie } from "@/src/pie/domain/business/baked-pie/mod.ts";

// Coordinator for [REQ] bakedPie.bake(BakeDto): BakedPieDto.
export async function bake(input: BakeDto): Promise<BakedPieDto> {

  // core — pure business logic, no I/O
  const out = bakeCore(input);

  return out.result;
}

// Pure business logic for bakedPie.bake — no I/O. Takes the
// request input; returns the result.
function bakeCore(input: BakeDto): { result: BakedPieDto } {
  const bakedPie = new BakedPie();
  return { result: { bakedPieId: `baked-${input.rawPieId}` } };
}
