// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { make } from "./mod.ts";

Deno.test("make — happy path", async () => {
  // TODO: implement happy path test
});

