// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { MakeFillingDto } from "@/src/pie/dto/make-filling.ts";
import type { FillingDto } from "@/src/pie/dto/filling.ts";
import { Filling } from "@/src/pie/domain/business/filling/mod.ts";

// Coordinator for [REQ] filling.make(MakeFillingDto): FillingDto.
export async function make(input: MakeFillingDto): Promise<FillingDto> {

  // core — pure business logic, no I/O
  const out = makeCore(input);

  return out.result;
}

// Pure business logic for filling.make — no I/O. Takes the
// request input; returns the result.
function makeCore(input: MakeFillingDto): { result: FillingDto } {
  const filling = new Filling();
  return { result: { fillingId: `filling-${input.fruitId}` } };
}
