// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Crust } from "./mod.ts";

Deno.test("Crust.toDto", () => {
  // TODO: test toDto
});
