// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the raw pie to bake
export class BakeDto {
  @IsString()
  rawPieId!: string;
}
