// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the baked pie
export class BakedPieDto {
  @IsString()
  bakedPieId!: string;
}
