// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a baked-pie identifier
// rune declares: [TYP] bakedPieId: string
export type BakedPieId = string;
