// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a rolled-crust identifier
// rune declares: [TYP] crustId: string
export type CrustId = string;
