// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a prepared-filling identifier
// rune declares: [TYP] fillingId: string
export type FillingId = string;
