// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a picked-fruit identifier
// rune declares: [TYP] fruitId: string
export type FruitId = string;
