// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the fruit to turn into filling
export class MakeFillingDto {
  @IsString()
  fruitId!: string;
}
