// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// which orchard to pick fruit from
export class OrchardDto {
  @IsString()
  orchard!: string;
}
