// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// an assembled-raw-pie identifier
// rune declares: [TYP] rawPieId: string
export type RawPieId = string;
