// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the filling the crust is rolled for
export class RollDoughDto {
  @IsString()
  fillingId!: string;
}
