// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsNumber } from "class-validator";

// how many slices the pie yielded
export class SlicesDto {
  @IsNumber()
  sliceCount!: number;
}
