// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a count of pie slices
// rune declares: [TYP] sliceCount: number
export type SliceCount = number;
