// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { SliceDto } from "@/src/pie/dto/slice.ts";
import type { SlicesDto } from "@/src/pie/dto/slices.ts";
import { Slices } from "@/src/pie/domain/business/slices/mod.ts";

// Coordinator for [REQ] slices.slice(SliceDto): SlicesDto.
export async function slice(input: SliceDto): Promise<SlicesDto> {

  // core — pure business logic, no I/O
  const out = sliceCore(input);

  return out.result;
}

// Pure business logic for slices.slice — no I/O. Takes the
// request input; returns the result.
function sliceCore(input: SliceDto): { result: SlicesDto } {
  const slices = new Slices();
  return { result: { sliceCount: 8 } };
}
