// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/keep";
import { OrchardDto } from "@/src/pie/dto/orchard.ts";
import { FruitDto } from "@/src/pie/dto/fruit.ts";
import { MakeFillingDto } from "@/src/pie/dto/make-filling.ts";
import { FillingDto } from "@/src/pie/dto/filling.ts";
import { RollDoughDto } from "@/src/pie/dto/roll-dough.ts";
import { CrustDto } from "@/src/pie/dto/crust.ts";
import { AssembleDto } from "@/src/pie/dto/assemble.ts";
import { RawPieDto } from "@/src/pie/dto/raw-pie.ts";
import { BakeDto } from "@/src/pie/dto/bake.ts";
import { BakedPieDto } from "@/src/pie/dto/baked-pie.ts";
import { SliceDto } from "@/src/pie/dto/slice.ts";
import { SlicesDto } from "@/src/pie/dto/slices.ts";
import { gather as fruitGather } from "@/src/pie/domain/coordinators/fruit-gather/mod.ts";
import { make as fillingMake } from "@/src/pie/domain/coordinators/filling-make/mod.ts";
import { roll as crustRoll } from "@/src/pie/domain/coordinators/crust-roll/mod.ts";
import { assemble as rawPieAssemble } from "@/src/pie/domain/coordinators/raw-pie-assemble/mod.ts";
import { bake as bakedPieBake } from "@/src/pie/domain/coordinators/baked-pie-bake/mod.ts";
import { slice as slicesSlice } from "@/src/pie/domain/coordinators/slices-slice/mod.ts";

@EndpointController("http")
export class HttpController {
  @Endpoint({ path: "gather-fruit", input: OrchardDto, output: FruitDto, order: 1 })
  gatherFruit(body: OrchardDto): Promise<FruitDto> {
    return fruitGather(body);
  }

  @Endpoint({ path: "make-filling", input: MakeFillingDto, output: FillingDto, order: 2, dependsOn: ["gatherFruit"], bind: {"fruitId":"gatherFruit.fruitId"} })
  makeFilling(body: MakeFillingDto): Promise<FillingDto> {
    return fillingMake(body);
  }

  @Endpoint({ path: "roll-dough", input: RollDoughDto, output: CrustDto, order: 3, dependsOn: ["makeFilling"], bind: {"fillingId":"makeFilling.fillingId"} })
  rollDough(body: RollDoughDto): Promise<CrustDto> {
    return crustRoll(body);
  }

  @Endpoint({ path: "assemble-pie", input: AssembleDto, output: RawPieDto, order: 4, dependsOn: ["rollDough"], bind: {"crustId":"rollDough.crustId"} })
  assemblePie(body: AssembleDto): Promise<RawPieDto> {
    return rawPieAssemble(body);
  }

  @Endpoint({ path: "bake-pie", input: BakeDto, output: BakedPieDto, order: 5, dependsOn: ["assemblePie"], bind: {"rawPieId":"assemblePie.rawPieId"} })
  bakePie(body: BakeDto): Promise<BakedPieDto> {
    return bakedPieBake(body);
  }

  @Endpoint({ path: "slice-pie", input: SliceDto, output: SlicesDto, order: 6, dependsOn: ["bakePie"], bind: {"bakedPieId":"bakePie.bakedPieId"} })
  slicePie(body: SliceDto): Promise<SlicesDto> {
    return slicesSlice(body);
  }
}

export const httpModule = endpointModule("Pie", [HttpController]);
