// Generated by rune manifest from src/pie/pie.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { AssembleDto } from "@/src/pie/dto/assemble.ts";
import type { RawPieDto } from "@/src/pie/dto/raw-pie.ts";
import { RawPie } from "@/src/pie/domain/business/raw-pie/mod.ts";

// Coordinator for [REQ] rawPie.assemble(AssembleDto): RawPieDto.
export async function assemble(input: AssembleDto): Promise<RawPieDto> {

  // core — pure business logic, no I/O
  const out = assembleCore(input);

  return out.result;
}

// Pure business logic for rawPie.assemble — no I/O. Takes the
// request input; returns the result.
function assembleCore(input: AssembleDto): { result: RawPieDto } {
  const rawPie = new RawPie();
  return { result: { rawPieId: `raw-${input.crustId}` } };
}
